export const ERP_COLOR_CODE = {
  ERP_APP_COLOR: '#251d50',
  ERP_ACTIVE_BUTTON: '#000000',
  ERP_DE_ACTIVE_BUTTON: '#c2bdbdff',
  ERP_REMOVE_BUTTON: '#ff3b30',
  ERP_CANCEL_BUTTON: '#f0f0f0',
  ERP_SUCCESS_BUTTON: '#34C759',
  ERP_INPUT_BACKGROUND: '#fafafa',
  ERP_TEXT_WHITE: '#FFF',
  ERP_TEXT_BLACK: '#000000',
  ERP_BACKGROUND: '#f5f5f5',
  ERP_WHITE: '#FFFFFF',
  ERP_BLACK: '#000000',
  ERP_BORDER: '#e0e0e0',
  ERP_ACTIVE_BACKGROUND: '#f0f8ff',
  ERP_ERROR: "#9d261d"
};

export const ERP_SCREEN_NAME = {
  ERP_LOGIN: 'Login',
};

export const ERP_SCREEN_HEADER_TITLE = {};
